---
kind: pipeline
name: nightly

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: ljoonal/drone-rust-ci:nightly-alpine
  commands:
  - cargo fetch

- name: fmt
  pull: always
  image: ljoonal/drone-rust-ci:nightly-alpine
  commands:
  - cargo fmt --check
  depends_on:
  - fetch

- name: clippy
  pull: always
  image: ljoonal/drone-rust-ci:nightly-alpine
  commands:
  - cargo clippy --all-features -Z unstable-options --future-incompat-report
  depends_on:
  - fetch

trigger:
  event:
  - push

---
kind: pipeline
name: stable

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo fetch

- name: spellcheck
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo spellcheck -m 1
  depends_on:
  - fetch

- name: clippy
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo clippy --all-features
  depends_on:
  - fetch

- name: fmt
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo fmt --check
  depends_on:
  - fetch

- name: deny
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo deny --all-features check
  depends_on:
  - fetch

- name: build
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo build --all-features
  depends_on:
  - deny

- name: test
  image: ljoonal/drone-rust-ci:alpine
  commands:
  - cargo test --all-features
  depends_on:
  - build

trigger:
  event:
  - push
