[package]
name = "neos"
version = "0.2.0-alpha.4"
edition = "2021"
license = "MPL-2.0"
authors = ["ljoonal"]
description = "NeosVR's API in rust"
repository = "https://git.ljoonal.xyz/ljoonal/neos_rs"
documentation = "https://docs.rs/neos"
keywords = ["neos", "neosvr", "api", "rest"]
categories = ["api-bindings", "games"]

include = ["src", "Cargo.toml", "LICENSE", "README.md"]

[badges]
maintenance = { status = "experimental" }

[lib]
name = "neos"
path = "src/lib.rs"

[features]
default = []
api_client = ["minreq"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", default-features = false }
chrono = { version = "0.4", features = ["serde"] }
strum = { version = "0.23", features = ["derive"] }

# The smallest fully featured HTTPS client that was found
[dependencies.minreq]
version = "2.5.1"
optional = true
features = ["https-rustls-probe", "json-using-serde"]

[dev-dependencies]
serde_json = { version = "1" }
once_cell = "^1.9"

[package.metadata.docs.rs]
features = ["api_client"]
rustdoc-args = ["--cfg", "nightly"]
