[package]
name = "neos"
version = "0.1.0-alpha.2"
edition = "2021"
license = "MPL-2.0"
authors = ["ljoonal"]
description = "Rust models of NeosVR's API"
repository = "https://git.ljoonal.xyz/ljoonal/neos_rs"
keywords = ["neos"]
categories = ["api-bindings", "games"]

[badges]
maintenance = { status = "experimental" }

[lib]
name = "neos"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", default-features = false }
chrono = { version = "0.4", features = ["serde"] }
strum = { version = "0.23", features = ["derive"] }

# The smallest fully featured HTTPS client that was found
minreq = { version = "2.5.1", optional = true, features = [
	"https-rustls-probe",
	"json-using-serde",
] }
serde_json = { version = "1", optional = true }


[dev-dependencies]
serde_json = { version = "1" }

[features]
default = []
api_client = ["minreq"]

[package.metadata.docs.rs]
features = ["api_client"]
